CREATE TABLE flights (
  id SERIAL PRIMARY KEY,
  flight_number VARCHAR(20) NOT NULL,         -- e.g., "CX520"
  airline VARCHAR(100) NOT NULL,              -- e.g., "Cathay Pacific"
  airplane_id VARCHAR(20),                    -- Unique plane identifier (e.g., "B789")
  airplane_model VARCHAR(100),                -- Plane model (e.g., "Boeing 787-9")
  departure_city VARCHAR(100) NOT NULL,
  departure_country VARCHAR(100) NOT NULL,
  arrival_city VARCHAR(100) NOT NULL,
  arrival_country VARCHAR(100) NOT NULL,
  departure_airport VARCHAR(10),
  arrival_airport VARCHAR(10),
  departure_time TIME NOT NULL,               -- Time of day only, no specific date
  arrival_time TIME NOT NULL,                 -- Time of day only, no specific date
  price DECIMAL(10,2) NOT NULL,
  available_seats INT NOT NULL,
  has_discount BOOLEAN DEFAULT FALSE,
  discount_rate DECIMAL(3,2) DEFAULT 0.00
);








INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX413', 'Cathay Pacific', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Santorini', 'Greece', 'HKG', 'N/A', '23:50:00', '14:12:00', 571.07, 153, TRUE, 0.2);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX103', 'Cathay Pacific', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Nairobi', 'Kenya', 'HKG', 'N/A', '17:15:00', '08:04:00', 1154.05, 255, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX594', 'Cathay Pacific', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Doha', 'Qatar', 'HKG', 'N/A', '19:48:00', '08:25:00', 170.78, 278, TRUE, 0.06);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX580', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '00:03:00', '11:43:00', 352.86, 290, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX397', 'Cathay Pacific', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Nairobi', 'Kenya', 'HKG', 'N/A', '10:12:00', '10:42:00', 1466.8, 247, TRUE, 0.07);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX716', 'Cathay Pacific', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Kuala Lumpur', 'Malaysia', 'HKG', 'N/A', '18:17:00', '10:53:00', 287.64, 212, TRUE, 0.06);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX732', 'Cathay Pacific', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Whistler', 'Canada', 'HKG', 'N/A', '20:03:00', '13:37:00', 1436.76, 103, TRUE, 0.08);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX364', 'Cathay Pacific', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '23:29:00', '03:33:00', 982.19, 277, TRUE, 0.09);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX697', 'Cathay Pacific', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '03:24:00', '00:13:00', 379.65, 171, TRUE, 0.22);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX892', 'Cathay Pacific', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Maldives', 'Maldives', 'HKG', 'N/A', '14:10:00', '01:03:00', 1433.84, 126, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX878', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '19:32:00', '22:21:00', 322.84, 247, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX863', 'Cathay Pacific', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Reykjavik', 'Iceland', 'HKG', 'N/A', '01:53:00', '22:29:00', 206.13, 116, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX653', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '18:55:00', '18:59:00', 938.85, 223, TRUE, 0.21);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX479', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '20:27:00', '12:39:00', 100.09, 76, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX218', 'Cathay Pacific', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Singapore', 'Singapore', 'HKG', 'N/A', '23:36:00', '19:54:00', 561.29, 171, TRUE, 0.1);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX713', 'Cathay Pacific', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '21:37:00', '03:26:00', 771.15, 196, TRUE, 0.13);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX590', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Maldives', 'Maldives', 'HKG', 'N/A', '02:36:00', '02:20:00', 281.47, 183, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX493', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '11:23:00', '03:50:00', 1470.03, 262, TRUE, 0.06);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX547', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Bali', 'Indonesia', 'HKG', 'N/A', '10:08:00', '02:54:00', 693.59, 72, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX242', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '16:25:00', '05:27:00', 1050.52, 204, TRUE, 0.12);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX614', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '16:51:00', '20:53:00', 164.27, 75, TRUE, 0.22);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX956', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Bali', 'Indonesia', 'HKG', 'N/A', '18:35:00', '20:54:00', 912.69, 203, TRUE, 0.08);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX134', 'Cathay Pacific', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Whistler', 'Canada', 'HKG', 'N/A', '12:06:00', '11:35:00', 1313.47, 272, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX771', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Singapore', 'Singapore', 'HKG', 'N/A', '04:39:00', '17:57:00', 278.55, 118, TRUE, 0.16);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX542', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Nagano', 'Japan', 'HKG', 'N/A', '12:55:00', '11:31:00', 668.64, 247, TRUE, 0.11);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX205', 'Cathay Pacific', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Whistler', 'Canada', 'HKG', 'N/A', '15:18:00', '09:56:00', 571.47, 94, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX935', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Nagano', 'Japan', 'HKG', 'N/A', '11:33:00', '08:59:00', 1180.22, 214, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX984', 'Cathay Pacific', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Aspen', 'USA', 'HKG', 'N/A', '09:23:00', '03:01:00', 1328.04, 262, TRUE, 0.12);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX433', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Kuala Lumpur', 'Malaysia', 'HKG', 'N/A', '13:17:00', '23:21:00', 240.82, 69, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX983', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Edinburgh', 'UK', 'HKG', 'N/A', '17:19:00', '00:22:00', 1446.77, 280, TRUE, 0.15);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX694', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '16:42:00', '23:24:00', 293.86, 251, TRUE, 0.08);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX410', 'Cathay Pacific', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Nagano', 'Japan', 'HKG', 'N/A', '17:25:00', '08:33:00', 480.77, 72, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX755', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Gold Coast', 'Australia', 'HKG', 'N/A', '10:54:00', '04:19:00', 406.21, 144, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX131', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Maldives', 'Maldives', 'HKG', 'N/A', '12:15:00', '12:08:00', 1001.36, 89, TRUE, 0.14);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX181', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '15:23:00', '04:12:00', 1188.75, 104, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX265', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Singapore', 'Singapore', 'HKG', 'N/A', '12:42:00', '08:38:00', 170.8, 72, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX526', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Reykjavik', 'Iceland', 'HKG', 'N/A', '05:10:00', '07:25:00', 924.05, 71, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX500', 'Cathay Pacific', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Doha', 'Qatar', 'HKG', 'N/A', '22:48:00', '09:39:00', 497.38, 168, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX296', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Singapore', 'Singapore', 'HKG', 'N/A', '02:28:00', '09:57:00', 1128.39, 295, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX564', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Edinburgh', 'UK', 'HKG', 'N/A', '23:57:00', '02:40:00', 1444.28, 165, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX775', 'Cathay Pacific', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Maldives', 'Maldives', 'HKG', 'N/A', '21:23:00', '05:08:00', 373.93, 228, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX882', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Kuala Lumpur', 'Malaysia', 'HKG', 'N/A', '18:20:00', '05:57:00', 993.39, 294, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX331', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Santorini', 'Greece', 'HKG', 'N/A', '04:54:00', '11:39:00', 505.61, 74, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX508', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Gold Coast', 'Australia', 'HKG', 'N/A', '20:25:00', '20:34:00', 1464.31, 58, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX309', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Oxford', 'UK', 'HKG', 'N/A', '22:44:00', '07:07:00', 511.35, 272, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX620', 'Cathay Pacific', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Doha', 'Qatar', 'HKG', 'N/A', '21:08:00', '04:34:00', 956.16, 280, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX336', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Nagano', 'Japan', 'HKG', 'N/A', '09:21:00', '14:03:00', 779.82, 180, TRUE, 0.15);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX946', 'Cathay Pacific', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Nagano', 'Japan', 'HKG', 'N/A', '04:44:00', '00:27:00', 1282.07, 206, TRUE, 0.12);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX605', 'Cathay Pacific', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Gold Coast', 'Australia', 'HKG', 'N/A', '23:49:00', '08:23:00', 1029.77, 104, TRUE, 0.08);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('CX544', 'Cathay Pacific', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Santorini', 'Greece', 'HKG', 'N/A', '03:44:00', '22:59:00', 874.78, 277, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX355', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Whistler', 'Canada', 'HKG', 'N/A', '05:17:00', '12:35:00', 253.1, 75, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX990', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '10:49:00', '16:28:00', 804.8, 191, TRUE, 0.07);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX216', 'Hong Kong Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Kuala Lumpur', 'Malaysia', 'HKG', 'N/A', '04:48:00', '11:31:00', 209.31, 57, TRUE, 0.23);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX436', 'Hong Kong Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Nairobi', 'Kenya', 'HKG', 'N/A', '11:57:00', '10:49:00', 693.64, 186, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX104', 'Hong Kong Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '00:31:00', '17:22:00', 235.93, 163, TRUE, 0.22);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX502', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Santorini', 'Greece', 'HKG', 'N/A', '06:33:00', '21:08:00', 1096.32, 294, TRUE, 0.08);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX387', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Bali', 'Indonesia', 'HKG', 'N/A', '07:47:00', '10:28:00', 618.44, 152, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX607', 'Hong Kong Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Bali', 'Indonesia', 'HKG', 'N/A', '17:05:00', '18:16:00', 227.8, 197, TRUE, 0.2);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX753', 'Hong Kong Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '20:06:00', '09:59:00', 883.4, 153, TRUE, 0.14);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX345', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Phuket', 'Thailand', 'HKG', 'N/A', '10:24:00', '06:25:00', 100.8, 172, TRUE, 0.13);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX963', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Maldives', 'Maldives', 'HKG', 'N/A', '21:43:00', '06:38:00', 123.63, 255, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX195', 'Hong Kong Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Phuket', 'Thailand', 'HKG', 'N/A', '14:46:00', '01:45:00', 1099.56, 146, TRUE, 0.23);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX344', 'Hong Kong Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Santorini', 'Greece', 'HKG', 'N/A', '17:03:00', '13:30:00', 522.24, 267, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX261', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Doha', 'Qatar', 'HKG', 'N/A', '15:16:00', '13:04:00', 472.45, 218, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX170', 'Hong Kong Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Bali', 'Indonesia', 'HKG', 'N/A', '20:52:00', '00:17:00', 112.16, 227, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX592', 'Hong Kong Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Santorini', 'Greece', 'HKG', 'N/A', '06:15:00', '17:57:00', 837.5, 196, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX292', 'Hong Kong Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '17:32:00', '19:03:00', 1018.02, 121, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX876', 'Hong Kong Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '06:24:00', '16:53:00', 1199.13, 258, TRUE, 0.21);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX426', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Singapore', 'Singapore', 'HKG', 'N/A', '21:32:00', '14:20:00', 393.0, 231, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX168', 'Hong Kong Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Edinburgh', 'UK', 'HKG', 'N/A', '00:11:00', '03:13:00', 545.57, 258, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX695', 'Hong Kong Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Reykjavik', 'Iceland', 'HKG', 'N/A', '02:15:00', '02:04:00', 1329.7, 193, TRUE, 0.06);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX304', 'Hong Kong Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '10:34:00', '22:36:00', 227.03, 132, TRUE, 0.18);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX945', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Edinburgh', 'UK', 'HKG', 'N/A', '09:49:00', '05:57:00', 289.21, 78, TRUE, 0.16);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX402', 'Hong Kong Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '04:46:00', '20:11:00', 716.93, 113, TRUE, 0.2);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX494', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Oxford', 'UK', 'HKG', 'N/A', '12:01:00', '13:44:00', 846.88, 207, TRUE, 0.09);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX639', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Nairobi', 'Kenya', 'HKG', 'N/A', '00:23:00', '10:54:00', 1236.65, 246, TRUE, 0.15);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX995', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '21:23:00', '09:25:00', 1009.74, 172, TRUE, 0.2);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX168', 'Hong Kong Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Edinburgh', 'UK', 'HKG', 'N/A', '05:59:00', '13:47:00', 121.49, 198, TRUE, 0.14);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX504', 'Hong Kong Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Aspen', 'USA', 'HKG', 'N/A', '14:36:00', '12:19:00', 174.17, 228, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX222', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '01:39:00', '21:14:00', 969.85, 274, TRUE, 0.08);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX426', 'Hong Kong Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Aspen', 'USA', 'HKG', 'N/A', '10:06:00', '05:04:00', 252.93, 235, TRUE, 0.17);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX820', 'Hong Kong Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Santorini', 'Greece', 'HKG', 'N/A', '13:58:00', '23:10:00', 1308.58, 89, TRUE, 0.25);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX622', 'Hong Kong Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '16:03:00', '09:12:00', 308.64, 87, TRUE, 0.16);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX682', 'Hong Kong Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Singapore', 'Singapore', 'HKG', 'N/A', '15:46:00', '06:08:00', 263.14, 126, TRUE, 0.05);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX213', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Nairobi', 'Kenya', 'HKG', 'N/A', '06:53:00', '07:54:00', 503.27, 95, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX238', 'Hong Kong Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Whistler', 'Canada', 'HKG', 'N/A', '21:21:00', '12:06:00', 207.23, 286, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX836', 'Hong Kong Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Bali', 'Indonesia', 'HKG', 'N/A', '00:42:00', '05:01:00', 759.79, 233, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX691', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Edinburgh', 'UK', 'HKG', 'N/A', '04:50:00', '22:33:00', 742.95, 251, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX769', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '12:05:00', '21:14:00', 153.75, 63, TRUE, 0.2);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX150', 'Hong Kong Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Doha', 'Qatar', 'HKG', 'N/A', '07:46:00', '09:05:00', 797.04, 220, TRUE, 0.2);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX198', 'Hong Kong Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Kuala Lumpur', 'Malaysia', 'HKG', 'N/A', '01:00:00', '09:09:00', 1489.76, 291, TRUE, 0.19);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX347', 'Hong Kong Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '19:04:00', '02:32:00', 263.66, 51, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX341', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '20:15:00', '16:21:00', 266.49, 201, TRUE, 0.18);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX703', 'Hong Kong Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Doha', 'Qatar', 'HKG', 'N/A', '16:37:00', '13:59:00', 417.32, 204, TRUE, 0.17);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX609', 'Hong Kong Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Singapore', 'Singapore', 'HKG', 'N/A', '01:44:00', '03:29:00', 908.3, 110, TRUE, 0.13);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX457', 'Hong Kong Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Doha', 'Qatar', 'HKG', 'N/A', '16:56:00', '02:16:00', 1193.26, 145, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX247', 'Hong Kong Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '07:52:00', '13:50:00', 516.69, 260, TRUE, 0.08);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX976', 'Hong Kong Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Maldives', 'Maldives', 'HKG', 'N/A', '22:31:00', '18:45:00', 1129.35, 218, TRUE, 0.12);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX526', 'Hong Kong Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '15:03:00', '17:14:00', 179.22, 186, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HX227', 'Hong Kong Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Phuket', 'Thailand', 'HKG', 'N/A', '20:59:00', '18:31:00', 1260.43, 171, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO400', 'HK Express', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Reykjavik', 'Iceland', 'HKG', 'N/A', '00:40:00', '10:19:00', 528.81, 290, TRUE, 0.08);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO717', 'HK Express', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Singapore', 'Singapore', 'HKG', 'N/A', '23:25:00', '09:05:00', 1100.7, 101, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO521', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Edinburgh', 'UK', 'HKG', 'N/A', '21:06:00', '02:02:00', 817.99, 179, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO951', 'HK Express', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '10:53:00', '06:05:00', 277.65, 171, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO484', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '01:11:00', '12:16:00', 228.16, 212, TRUE, 0.1);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO807', 'HK Express', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Nagano', 'Japan', 'HKG', 'N/A', '15:39:00', '02:46:00', 1010.24, 57, TRUE, 0.1);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO906', 'HK Express', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '20:23:00', '01:15:00', 1105.38, 161, TRUE, 0.16);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO374', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '12:21:00', '05:14:00', 1417.49, 179, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO470', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '13:27:00', '10:23:00', 475.55, 281, TRUE, 0.22);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO594', 'HK Express', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Reykjavik', 'Iceland', 'HKG', 'N/A', '07:57:00', '06:54:00', 871.81, 129, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO151', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Gold Coast', 'Australia', 'HKG', 'N/A', '19:45:00', '18:58:00', 681.88, 190, TRUE, 0.08);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO899', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Reykjavik', 'Iceland', 'HKG', 'N/A', '15:29:00', '12:25:00', 172.68, 293, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO489', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Nagano', 'Japan', 'HKG', 'N/A', '00:21:00', '06:39:00', 122.81, 286, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO444', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Nairobi', 'Kenya', 'HKG', 'N/A', '17:59:00', '16:29:00', 1201.0, 187, TRUE, 0.23);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO537', 'HK Express', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '17:03:00', '04:57:00', 731.81, 189, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO388', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '15:44:00', '05:48:00', 864.72, 142, TRUE, 0.09);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO429', 'HK Express', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Phuket', 'Thailand', 'HKG', 'N/A', '01:30:00', '10:51:00', 1264.62, 118, TRUE, 0.17);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO572', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '09:45:00', '14:47:00', 1405.94, 97, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO841', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Gold Coast', 'Australia', 'HKG', 'N/A', '02:36:00', '22:28:00', 1458.21, 87, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO764', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Aspen', 'USA', 'HKG', 'N/A', '02:59:00', '12:47:00', 1283.16, 241, TRUE, 0.19);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO624', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Santorini', 'Greece', 'HKG', 'N/A', '04:27:00', '16:29:00', 621.29, 238, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO490', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Santorini', 'Greece', 'HKG', 'N/A', '13:54:00', '10:10:00', 390.85, 276, TRUE, 0.19);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO676', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Doha', 'Qatar', 'HKG', 'N/A', '03:11:00', '01:06:00', 1405.3, 263, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO420', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '12:06:00', '10:55:00', 303.28, 224, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO411', 'HK Express', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '02:57:00', '19:10:00', 378.32, 124, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO513', 'HK Express', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Gold Coast', 'Australia', 'HKG', 'N/A', '23:55:00', '00:43:00', 925.06, 225, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO811', 'HK Express', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Nagano', 'Japan', 'HKG', 'N/A', '13:45:00', '03:07:00', 144.8, 197, TRUE, 0.1);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO850', 'HK Express', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '15:05:00', '17:15:00', 755.69, 261, TRUE, 0.13);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO394', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Santorini', 'Greece', 'HKG', 'N/A', '12:00:00', '14:26:00', 225.01, 192, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO460', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '23:56:00', '02:29:00', 784.3, 153, TRUE, 0.22);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO697', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '03:27:00', '11:06:00', 919.52, 195, TRUE, 0.09);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO768', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Kuala Lumpur', 'Malaysia', 'HKG', 'N/A', '09:35:00', '16:53:00', 1374.22, 67, TRUE, 0.17);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO632', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '16:57:00', '07:35:00', 1148.5, 289, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO123', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '07:59:00', '01:57:00', 1229.14, 111, TRUE, 0.1);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO254', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Oxford', 'UK', 'HKG', 'N/A', '06:27:00', '00:36:00', 1290.19, 239, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO517', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Reykjavik', 'Iceland', 'HKG', 'N/A', '20:15:00', '20:56:00', 1330.36, 280, TRUE, 0.14);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO869', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Nagano', 'Japan', 'HKG', 'N/A', '14:28:00', '02:33:00', 1214.23, 82, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO594', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Maldives', 'Maldives', 'HKG', 'N/A', '20:01:00', '00:49:00', 607.77, 165, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO529', 'HK Express', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Gold Coast', 'Australia', 'HKG', 'N/A', '14:13:00', '07:23:00', 793.68, 62, TRUE, 0.12);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO970', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Aspen', 'USA', 'HKG', 'N/A', '11:01:00', '10:53:00', 1462.96, 141, TRUE, 0.23);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO713', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Bali', 'Indonesia', 'HKG', 'N/A', '16:24:00', '11:04:00', 584.97, 191, TRUE, 0.08);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO823', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '13:44:00', '14:21:00', 484.7, 269, TRUE, 0.22);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO307', 'HK Express', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Whistler', 'Canada', 'HKG', 'N/A', '21:53:00', '06:10:00', 1163.24, 220, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO623', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Bali', 'Indonesia', 'HKG', 'N/A', '12:49:00', '01:18:00', 941.75, 54, TRUE, 0.22);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO837', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '13:08:00', '13:15:00', 637.37, 279, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO148', 'HK Express', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '15:30:00', '03:17:00', 288.49, 213, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO631', 'HK Express', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Aspen', 'USA', 'HKG', 'N/A', '06:14:00', '02:43:00', 1132.25, 199, TRUE, 0.17);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO343', 'HK Express', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '10:47:00', '15:33:00', 1407.88, 63, TRUE, 0.19);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO571', 'HK Express', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Reykjavik', 'Iceland', 'HKG', 'N/A', '11:30:00', '20:50:00', 269.03, 250, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('UO309', 'HK Express', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '04:15:00', '18:44:00', 258.75, 213, TRUE, 0.19);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB111', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Oxford', 'UK', 'HKG', 'N/A', '03:12:00', '16:38:00', 954.19, 91, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB430', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Nairobi', 'Kenya', 'HKG', 'N/A', '23:31:00', '12:24:00', 964.45, 183, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB358', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '06:15:00', '17:15:00', 1269.7, 235, TRUE, 0.14);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB291', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '09:26:00', '03:18:00', 680.07, 280, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB488', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Maldives', 'Maldives', 'HKG', 'N/A', '12:24:00', '07:11:00', 1381.33, 207, TRUE, 0.16);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB183', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Doha', 'Qatar', 'HKG', 'N/A', '01:30:00', '02:35:00', 416.12, 249, TRUE, 0.12);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB884', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Singapore', 'Singapore', 'HKG', 'N/A', '00:55:00', '06:42:00', 811.04, 127, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB741', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Bali', 'Indonesia', 'HKG', 'N/A', '11:42:00', '13:35:00', 1177.75, 77, TRUE, 0.07);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB882', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '13:56:00', '09:33:00', 1098.72, 149, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB786', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Phuket', 'Thailand', 'HKG', 'N/A', '22:31:00', '09:37:00', 471.85, 141, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB643', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '03:10:00', '18:43:00', 1497.85, 170, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB151', 'Greater Bay Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Nagano', 'Japan', 'HKG', 'N/A', '10:54:00', '15:37:00', 1335.75, 50, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB847', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '07:03:00', '23:30:00', 1038.03, 117, TRUE, 0.18);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB147', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Phuket', 'Thailand', 'HKG', 'N/A', '20:47:00', '09:41:00', 175.21, 230, TRUE, 0.17);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB165', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '02:44:00', '20:28:00', 731.25, 235, TRUE, 0.12);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB966', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Doha', 'Qatar', 'HKG', 'N/A', '15:10:00', '14:31:00', 1220.71, 298, TRUE, 0.11);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB734', 'Greater Bay Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Phuket', 'Thailand', 'HKG', 'N/A', '10:43:00', '05:38:00', 217.62, 146, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB652', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '01:04:00', '15:53:00', 825.59, 218, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB455', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Kuala Lumpur', 'Malaysia', 'HKG', 'N/A', '23:44:00', '12:41:00', 418.87, 108, TRUE, 0.08);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB611', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '23:53:00', '18:49:00', 567.45, 137, TRUE, 0.23);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB172', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Nagano', 'Japan', 'HKG', 'N/A', '08:07:00', '14:49:00', 458.72, 53, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB935', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Santorini', 'Greece', 'HKG', 'N/A', '21:17:00', '11:19:00', 851.24, 269, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB400', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '21:50:00', '10:37:00', 772.31, 59, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB933', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Phuket', 'Thailand', 'HKG', 'N/A', '15:18:00', '23:06:00', 376.4, 55, TRUE, 0.13);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB705', 'Greater Bay Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '09:21:00', '09:15:00', 183.04, 97, TRUE, 0.19);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB444', 'Greater Bay Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Cancun', 'Mexico', 'HKG', 'N/A', '06:50:00', '05:38:00', 201.79, 125, TRUE, 0.16);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB836', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Nairobi', 'Kenya', 'HKG', 'N/A', '12:23:00', '23:42:00', 856.47, 174, TRUE, 0.2);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB930', 'Greater Bay Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Maldives', 'Maldives', 'HKG', 'N/A', '08:28:00', '00:39:00', 837.11, 271, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB753', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '10:17:00', '15:37:00', 489.75, 140, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB492', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Whistler', 'Canada', 'HKG', 'N/A', '02:58:00', '04:31:00', 822.58, 120, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB897', 'Greater Bay Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '02:08:00', '08:01:00', 948.08, 63, TRUE, 0.24);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB490', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Phuket', 'Thailand', 'HKG', 'N/A', '06:39:00', '10:14:00', 423.27, 54, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB773', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Bali', 'Indonesia', 'HKG', 'N/A', '12:42:00', '08:22:00', 405.62, 166, TRUE, 0.2);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB867', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'New York', 'USA', 'HKG', 'N/A', '00:11:00', '06:10:00', 498.89, 262, TRUE, 0.11);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB303', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Reykjavik', 'Iceland', 'HKG', 'N/A', '22:06:00', '14:22:00', 218.38, 276, TRUE, 0.06);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB167', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Doha', 'Qatar', 'HKG', 'N/A', '11:00:00', '04:59:00', 324.93, 194, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB356', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Oxford', 'UK', 'HKG', 'N/A', '06:55:00', '23:06:00', 1014.17, 266, TRUE, 0.06);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB935', 'Greater Bay Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Queenstown', 'New Zealand', 'HKG', 'N/A', '15:49:00', '09:17:00', 756.87, 108, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB276', 'Greater Bay Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Dubai', 'UAE', 'HKG', 'N/A', '03:03:00', '18:02:00', 1312.71, 167, TRUE, 0.16);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB909', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Singapore', 'Singapore', 'HKG', 'N/A', '22:06:00', '14:06:00', 715.16, 238, TRUE, 0.15);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB804', 'Greater Bay Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Maldives', 'Maldives', 'HKG', 'N/A', '16:23:00', '09:39:00', 515.69, 253, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB388', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Aspen', 'USA', 'HKG', 'N/A', '23:18:00', '19:25:00', 1419.81, 87, TRUE, 0.16);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB997', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Aspen', 'USA', 'HKG', 'N/A', '17:34:00', '17:05:00', 1218.44, 184, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB825', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Edinburgh', 'UK', 'HKG', 'N/A', '00:44:00', '07:46:00', 691.97, 287, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB322', 'Greater Bay Airlines', 'B789', 'Boeing 787-9', 'Hong Kong', 'Hong Kong', 'Oxford', 'UK', 'HKG', 'N/A', '20:55:00', '00:55:00', 661.09, 236, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB389', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Berlin', 'Germany', 'HKG', 'N/A', '15:00:00', '02:16:00', 880.95, 266, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB916', 'Greater Bay Airlines', 'A320', 'Airbus A320neo', 'Hong Kong', 'Hong Kong', 'Maldives', 'Maldives', 'HKG', 'N/A', '02:20:00', '06:36:00', 423.43, 279, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB588', 'Greater Bay Airlines', 'B777', 'Boeing 777-300ER', 'Hong Kong', 'Hong Kong', 'Reykjavik', 'Iceland', 'HKG', 'N/A', '11:04:00', '14:08:00', 319.02, 205, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB778', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Reykjavik', 'Iceland', 'HKG', 'N/A', '01:20:00', '11:28:00', 171.82, 50, FALSE, 0.0);
INSERT INTO flights (flight_number, airline, airplane_id, airplane_model, departure_city, departure_country, arrival_city, arrival_country, departure_airport, arrival_airport, departure_time, arrival_time, price, available_seats, has_discount, discount_rate)
VALUES ('HB580', 'Greater Bay Airlines', 'A350', 'Airbus A350', 'Hong Kong', 'Hong Kong', 'Gold Coast', 'Australia', 'HKG', 'N/A', '13:58:00', '09:36:00', 805.44, 111, FALSE, 0.0);